# Generated by Django 5.2.17 on 2026-09-15 16:33

import core.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("window_started", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_attempts",
            },
        ),
        migrations.CreateModel(
            name="CustomService",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("price_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "custom_services",
            },
        ),
        migrations.CreateModel(
            name="InfluencerPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("price_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("video_allowance", models.PositiveIntegerField(blank=True, null=True)),
                ("revision_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("priority", models.BooleanField(default=False)),
                ("dedicated_editor", models.BooleanField(default=False)),
                ("services", models.JSONField(default=list)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "influencer_packages",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("plan", "Plan"), ("custom", "Custom")], default="custom", max_length=12
                    ),
                ),
                ("terms_snapshot", models.JSONField(default=dict)),
                ("total_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="UploadPolicy",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("max_bytes", models.PositiveBigIntegerField()),
                ("allowed_types", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "upload_policy",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined"),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[("client", "Client"), ("editor", "Editor"), ("admin", "Admin")],
                        default="client",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=60)),
                ("provider_reference", models.CharField(max_length=200)),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="core.order"
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slot", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("price_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("features", models.JSONField(default=list)),
                ("revision_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("delivery_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_limit_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "plans",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("slot__gte", 1), ("slot__lte", 3)), name="three_plan_slots"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="plan",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.plan"
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("requirements", models.TextField(blank=True, max_length=10000)),
                ("selected_services", models.JSONField(default=list)),
                ("reference_notes", models.TextField(blank=True, max_length=5000)),
                (
                    "song_choice",
                    models.CharField(
                        choices=[
                            ("provide", "I will provide my own song"),
                            ("known", "I already have a song"),
                            ("suggest", "Suggest a song for me"),
                        ],
                        default="suggest",
                        max_length=20,
                    ),
                ),
                ("song_information", models.TextField(blank=True, max_length=2000)),
                ("call_before", models.BooleanField(default=False)),
                ("call_after", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("payment_pending", "Payment pending"),
                            ("payment_completed", "Payment completed"),
                            ("awaiting_assignment", "Awaiting editor assignment"),
                            ("editor_assigned", "Editor assigned"),
                            ("editing", "Editing in progress"),
                            ("draft_uploaded", "Draft uploaded"),
                            ("awaiting_review", "Awaiting client review"),
                            ("revision_requested", "Revision requested"),
                            ("revision_in_progress", "Revision in progress"),
                            ("final_uploaded", "Final video uploaded"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="payment_pending",
                        max_length=30,
                    ),
                ),
                ("payment_completed_at", models.DateTimeField(blank=True, null=True)),
                ("expected_delivery_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="projects", to="core.client"
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="order", to="core.project"
            ),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=240)),
                ("object_key", models.CharField(max_length=300, unique=True)),
                ("storage_version", models.CharField(blank=True, max_length=200)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("source", "Source video"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("reference", "Reference"),
                            ("asset", "Other asset"),
                            ("draft", "Edited draft"),
                            ("final", "Final video"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ready", "Ready"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derivatives",
                        to="core.file",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="files", to="core.project"
                    ),
                ),
            ],
            options={
                "db_table": "files",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True)),
                ("is_final", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("file", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="core.file")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_versions",
            },
        ),
        migrations.CreateModel(
            name="RevisionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("instructions", models.TextField()),
                ("status", models.CharField(default="requested", max_length=20)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="core.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.projectversion"),
                ),
            ],
            options={
                "db_table": "revision_requests",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("terms_snapshot", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.client")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.influencerpackage"
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="unique_email_case_insensitive"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["client", "editor", "admin"])), name="valid_user_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_reference"), name="unique_provider_payment"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectversion",
            constraint=models.UniqueConstraint(fields=("project", "number"), name="unique_project_version"),
        ),
    ]
