# Generated by Django 5.2.17 on 2026-09-16 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommercePolicy",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("custom_base_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("custom_revision_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("custom_delivery_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("custom_duration_limit_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("custom_priority", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("terms", models.TextField(blank=True, max_length=12000)),
                ("delivery_terms", models.TextField(blank=True, max_length=4000)),
                ("refund_terms", models.TextField(blank=True, max_length=4000)),
                ("tax_terms", models.TextField(blank=True, max_length=4000)),
                ("quotes_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "commerce_policy",
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("id", 1)), name="one_commerce_policy")
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot", models.JSONField()),
                ("total_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="quotes", to="core.order"
                    ),
                ),
            ],
            options={
                "db_table": "order_quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=60)),
                ("event_id", models.CharField(max_length=200)),
                ("payload_digest", models.CharField(max_length=64)),
                ("outcome", models.CharField(max_length=20)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="events", to="core.payment"
                    ),
                ),
            ],
            options={
                "db_table": "payment_events",
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "event_id"), name="unique_payment_event")
                ],
            },
        ),
    ]
