# Generated by Django 5.2.17 on 2026-09-17 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_commercepolicy_orderquote_paymentevent"),
        ("operations", "0003_assignmentpolicy_assignmentqueue_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercepolicy",
            name="review_rule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("latest_request_v1", "One revision per request; review and accept latest submission")
                ],
                help_text="Owner-approved rule for new quotes only. Blank disables review actions. Excess revisions require a separate agreement; acceptance is final.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="projectversion",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="operations.editorassignment",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryAcceptance",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("terms_snapshot", models.JSONField(default=dict)),
                ("earning_status", models.CharField(default="pending_policy", max_length=30)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operations.editorassignment"
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptance",
                        to="core.project",
                    ),
                ),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.projectversion"
                    ),
                ),
            ],
            options={
                "db_table": "delivery_acceptances",
            },
        ),
    ]
