# Generated by Django 5.2.17 on 2026-09-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commercepolicy_review_rule_projectversion_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='song_choice',
            field=models.CharField(choices=[('provide', 'I will provide my own song'), ('suggest', 'Suggest a song for me'), ('both', 'I will provide a song and would also like editor suggestions')], default='suggest', max_length=20),
        ),
    ]
