# Generated by Django 5.2.17 on 2026-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='colour_grading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='quality_enhancement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='reel_duration',
            field=models.CharField(blank=True, choices=[('20_30', '20–30 seconds'), ('30_50', '30–50 seconds'), ('60_plus', '60+ seconds'), ('120_plus', '2 minutes+')], max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='wants_wording',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='wording_direction',
            field=models.CharField(blank=True, choices=[('own_font', 'I have my own font'), ('font_inspiration', 'I will upload font inspiration'), ('match_reference', 'Same as the reference'), ('editor_choice', 'Editor’s choice')], max_length=24),
        ),
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('source', 'Source video'), ('image', 'Image'), ('audio', 'Audio'), ('reference', 'Reference'), ('font_reference', 'Font inspiration'), ('asset', 'Other asset'), ('draft', 'Edited draft'), ('final', 'Final video')], max_length=20),
        ),
    ]
