# Generated by Django 5.2.17 on 2026-09-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_colour_grading_project_quality_enhancement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservice',
            name='code',
            field=models.CharField(blank=True, choices=[('colour_grading', 'Colour grading'), ('quality_enhancement', 'Quality enhancement'), ('duration_20_30', 'Duration: 20–30 seconds'), ('duration_30_50', 'Duration: 30–50 seconds'), ('duration_60_plus', 'Duration: 60+ seconds'), ('duration_120_plus', 'Duration: 2 minutes+'), ('wording', 'Wording / on-screen text')], max_length=32, null=True, unique=True),
        ),
    ]
