# Generated by Django 5.2.17 on 2026-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customservice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='font_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
