# Generated by Django 5.2.17 on 2026-09-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20260928_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='song_choice',
            field=models.CharField(choices=[('provide', 'I will provide my own song'), ('suggest', 'Suggest a song for me'), ('both', "I will provide my own song and would also like editor's suggestion")], default='suggest', max_length=20),
        ),
    ]
