# Generated by Django 5.2.17 on 2026-09-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_project_song_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pricing_period',
            field=models.CharField(choices=[('per_reel', 'Per Reel'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='per_reel', max_length=12),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_price_minor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_price_minor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
