# Generated by Django 5.2.17 on 2026-10-06 16:56

import django.core.validators
from django.db import migrations, models


def seed_quotation_features(apps, schema_editor):
    QuotationFeature = apps.get_model("core", "QuotationFeature")
    scores = [
        ("colour_grading", 4, 4, 4),
        ("quality_enhancement", 3, 4, 3),
        ("duration", 1, 5, 2),
        ("font_option", 2, 3, 2),
        ("song_option", 3, 4, 3),
        ("overlays", 4, 4, 4),
        ("beat_sync", 5, 5, 5),
    ]
    QuotationFeature.objects.using(schema_editor.connection.alias).bulk_create(
        [
            QuotationFeature(
                code=code,
                time_score=time_score,
                importance_score=importance_score,
                complexity_score=complexity_score,
                multiplier="1.000",
            )
            for code, time_score, importance_score, complexity_score in scores
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_pricing_period_plan_monthly_price_minor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('colour_grading', 'Colour grading'), ('quality_enhancement', 'Quality enhancement'), ('duration', 'Reel duration'), ('font_option', 'Font option'), ('song_option', 'Song option'), ('overlays', 'Overlays'), ('beat_sync', 'Beat sync')], max_length=32, unique=True)),
                ('time_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('importance_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('complexity_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('multiplier', models.DecimalField(decimal_places=3, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quotation_features',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_quotation_features, migrations.RunPython.noop),
        migrations.AddField(
            model_name='commercepolicy',
            name='quotation_complexity_weight',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='commercepolicy',
            name='quotation_engine_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commercepolicy',
            name='quotation_importance_weight',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='commercepolicy',
            name='quotation_max_minor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercepolicy',
            name='quotation_min_minor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercepolicy',
            name='quotation_point_minor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercepolicy',
            name='quotation_time_weight',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='project',
            name='beat_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='overlays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='quotation_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
