# Generated by Django 5.2.17 on 2026-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_quotationfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercepolicy',
            name='pricing_context',
            field=models.CharField(choices=[('unconfigured', 'Unconfigured'), ('test', 'Test only'), ('production', 'Production')], default='unconfigured', max_length=20),
        ),
    ]
