# Generated by Django 5.2.17 on 2026-10-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_commercepolicy_pricing_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_auth_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
