# Generated by Django 5.2.17 on 2026-09-15 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=30)),
                ("experience", models.TextField(max_length=5000)),
                ("tools", models.CharField(max_length=500)),
                ("portfolio", models.URLField(max_length=500)),
                ("previous_work", models.TextField(max_length=5000)),
                ("expertise", models.CharField(max_length=1000)),
                ("other_information", models.TextField(blank=True, max_length=5000)),
                ("approved", models.BooleanField(default=False)),
                ("workload_capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_editors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "editors",
            },
        ),
        migrations.CreateModel(
            name="EditorProficiency",
            fields=[
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criteria", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "editor_proficiency",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_key", models.CharField(max_length=200, unique=True)),
                ("message", models.CharField(max_length=500)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="ProjectComplexity",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule_version", models.CharField(blank=True, max_length=100)),
                ("internal_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "project_complexity",
            },
        ),
        migrations.CreateModel(
            name="RedemptionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.PositiveBigIntegerField()),
                ("status", models.CharField(default="requested", max_length=20)),
                ("payout_reference", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "redemption_requests",
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admins",
            },
        ),
        migrations.CreateModel(
            name="AssignmentQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="waiting", max_length=20)),
                (
                    "project",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="core.project"),
                ),
            ],
            options={
                "db_table": "assignment_queue",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=100)),
                ("target_id", models.CharField(max_length=100)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EditorAvailability",
            fields=[
                (
                    "editor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="availability",
                        serialize=False,
                        to="operations.editor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                            ("on_leave", "On leave"),
                            ("temporarily_unavailable", "Temporarily unavailable"),
                        ],
                        default="offline",
                        max_length=30,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "editor_availability",
            },
        ),
        migrations.CreateModel(
            name="CallRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[("before", "Before editing"), ("after", "After draft")], max_length=20
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="requested", max_length=20)),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.project"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.editor",
                    ),
                ),
            ],
            options={
                "db_table": "call_requests",
            },
        ),
        migrations.CreateModel(
            name="EditorAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="operations.editor",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "db_table": "editor_assignments",
            },
        ),
        migrations.CreateModel(
            name="EditorCoins",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("earning_rule", models.JSONField(default=dict)),
                (
                    "editor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to="operations.editor",
                    ),
                ),
            ],
            options={
                "db_table": "editor_coins",
            },
        ),
        migrations.CreateModel(
            name="CoinTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_key", models.CharField(max_length=200, unique=True)),
                ("amount", models.BigIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("credit", "Credit"),
                            ("reserve", "Reserved"),
                            ("redeem", "Redeemed"),
                            ("release", "Released"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rule_snapshot", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.project"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="operations.editorcoins",
                    ),
                ),
            ],
            options={
                "db_table": "coin_transactions",
            },
        ),
        migrations.CreateModel(
            name="RoundRobinState",
            fields=[
                (
                    "proficiency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="operations.editorproficiency",
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "round_robin_state",
            },
        ),
        migrations.AddConstraint(
            model_name="editorproficiency",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__in", ["beginner", "intermediate", "advanced"])),
                name="valid_proficiency",
            ),
        ),
        migrations.AddField(
            model_name="editor",
            name="proficiency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="operations.editorproficiency",
            ),
        ),
        migrations.AddField(
            model_name="assignmentqueue",
            name="proficiency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operations.editorproficiency"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.project"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="projectcomplexity",
            name="overridden_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="projectcomplexity",
            name="proficiency",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="operations.editorproficiency"
            ),
        ),
        migrations.AddField(
            model_name="projectcomplexity",
            name="project",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="core.project"),
        ),
        migrations.AddField(
            model_name="redemptionrequest",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="redemptions",
                to="operations.editorcoins",
            ),
        ),
        migrations.AddField(
            model_name="cointransaction",
            name="redemption",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="operations.redemptionrequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="editorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("project",),
                name="one_current_assignment",
            ),
        ),
        migrations.AddField(
            model_name="roundrobinstate",
            name="last_editor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="operations.editor"
            ),
        ),
        migrations.AddConstraint(
            model_name="editor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved", False),
                    models.Q(("approved_by__isnull", False), ("proficiency__isnull", False)),
                    _connector="OR",
                ),
                name="approved_editor_has_review",
            ),
        ),
    ]
