# Generated by Django 5.2.17 on 2026-09-16 16:26

from django.db import migrations, models


def seed_policy(apps, schema_editor):
    apps.get_model("operations", "AssignmentPolicy").objects.using(
        schema_editor.connection.alias
    ).get_or_create(pk=1)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_commercepolicy_orderquote_paymentevent"),
        ("operations", "0002_proficiency_levels"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentPolicy",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("manual_enabled", models.BooleanField(default=False)),
                ("automatic_enabled", models.BooleanField(default=False)),
                (
                    "busy_strategy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("skip", "Skip to next eligible editor"),
                            ("wait", "Wait for the next editor in rotation"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "manual_pointer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("preserve", "Keep the rotation position"),
                            ("advance", "Advance rotation to the manually selected editor"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "matching",
                    models.CharField(
                        blank=True,
                        choices=[("exact", "Same proficiency only; no cross-level fallback")],
                        max_length=20,
                    ),
                ),
                (
                    "capacity_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "open_assignments",
                                "All open assigned projects, including client review and revisions",
                            )
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "roster_order",
                    models.CharField(
                        blank=True,
                        choices=[("joined", "Registration order; new editors join at the end")],
                        max_length=20,
                    ),
                ),
                (
                    "queue_order",
                    models.CharField(
                        blank=True, choices=[("paid_at", "Oldest confirmed payment first")], max_length=20
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assignment_policy",
            },
        ),
        migrations.AddField(
            model_name="assignmentqueue",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assignmentqueue",
            name="blocked_reason",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="assignmentqueue",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="editorassignment",
            name="policy_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="projectcomplexity",
            name="revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="assignmentqueue",
            index=models.Index(fields=["status", "created_at"], name="assignment_queue_wait_idx"),
        ),
        migrations.AddConstraint(
            model_name="assignmentpolicy",
            constraint=models.CheckConstraint(condition=models.Q(("id", 1)), name="one_assignment_policy"),
        ),
        migrations.RunPython(seed_policy, migrations.RunPython.noop),
    ]
