# Generated by Django 5.2.17 on 2026-09-17 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_disabled_policy(apps, schema_editor):
    apps.get_model("operations", "EarningPolicy").objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commercepolicy_review_rule_projectversion_assignment_and_more'),
        ('operations', '0003_assignmentpolicy_assignmentqueue_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('rule', models.CharField(blank=True, choices=[('fixed_whole_v1', 'Fixed whole coins per accepted order')], max_length=30)),
                ('plan_1_coins', models.PositiveBigIntegerField(blank=True, null=True)),
                ('plan_2_coins', models.PositiveBigIntegerField(blank=True, null=True)),
                ('plan_3_coins', models.PositiveBigIntegerField(blank=True, null=True)),
                ('custom_coins', models.PositiveBigIntegerField(blank=True, null=True)),
                ('release_mode', models.CharField(blank=True, choices=[('manual', 'Admin verifies and releases')], max_length=20)),
                ('redemptions_enabled', models.BooleanField(default=False)),
                ('redemption_minimum', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'earning_policy',
            },
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name='cointransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='nonzero_coin_entry'),
        ),
        migrations.AddConstraint(
            model_name='earningpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='one_earning_policy'),
        ),
        migrations.RunPython(seed_disabled_policy, migrations.RunPython.noop),
    ]
