# Generated by Django 5.2.17 on 2026-09-17 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_earningpolicy_redemptionrequest_decided_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrequest',
            name='request_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='redemptionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('payout_reference',), name='unique_paid_payout_reference'),
        ),
    ]
