# Generated by Django 5.2.17 on 2026-09-18 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commercepolicy_review_rule_projectversion_assignment_and_more'),
        ('operations', '0005_redemptionrequest_request_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='callrequest',
            constraint=models.UniqueConstraint(fields=('project', 'stage'), name='one_call_per_project_stage'),
        ),
    ]
