# Generated by Django 5.2.17 on 2026-09-18 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commercepolicy_review_rule_projectversion_assignment_and_more'),
        ('operations', '0007_projectmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectmessage',
            index=models.Index(fields=['project', '-created_at', '-id'], name='message_project_cursor_idx'),
        ),
    ]
