# Generated by Django 5.2.17 on 2026-09-18 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commercepolicy_review_rule_projectversion_assignment_and_more'),
        ('operations', '0008_projectmessage_message_project_cursor_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at', '-id'], name='notice_recipient_cursor_idx'),
        ),
    ]
