# Generated by Django 5.2.17 on 2026-09-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_notification_notice_recipient_cursor_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='login_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
