# Generated by Django 5.2.17 on 2026-09-19 14:33

import uuid

import operations.models
from django.db import migrations, models


def populate_editor_login_ids(apps, schema_editor):
    Editor = apps.get_model("operations", "Editor")
    for editor in Editor.objects.filter(login_id__isnull=True).iterator():
        editor.login_id = f"VED-{uuid.uuid4().hex[:10].upper()}"
        editor.save(update_fields=["login_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_editor_login_id'),
    ]

    operations = [
        migrations.RunPython(populate_editor_login_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='editor',
            name='login_id',
            field=models.CharField(default=operations.models.new_editor_login_id, editable=False, max_length=20, unique=True),
        ),
    ]
