# Generated by Django 5.2.17 on 2026-09-23 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_held_deliveries(apps, schema_editor):
    Notification = apps.get_model("operations", "Notification")
    NotificationDelivery = apps.get_model("operations", "NotificationDelivery")
    NotificationDelivery.objects.bulk_create(
        [
            NotificationDelivery(notification_id=notification_id, state="held")
            for notification_id in Notification.objects.values_list("id", flat=True).iterator()
        ],
        batch_size=500,
        ignore_conflicts=True,
    )


def remove_backfilled_deliveries(apps, schema_editor):
    apps.get_model("operations", "NotificationDelivery").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_alter_editor_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('state', models.CharField(choices=[('held', 'Held until delivery is enabled'), ('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Retry scheduled'), ('cancelled', 'Cancelled')], default='held', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='operations.notification')),
            ],
            options={
                'db_table': 'notification_deliveries',
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='notice_delivery_due_idx')],
            },
        ),
        migrations.RunPython(backfill_held_deliveries, remove_backfilled_deliveries),
    ]
