# Generated by Django 5.2.17 on 2026-09-23 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customservice_code'),
        ('operations', '0012_notificationdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('project', 'Project help'), ('payment', 'Payment question'), ('account', 'Account help'), ('technical', 'Technical problem'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('request_key', models.UUIDField(unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_requests', to='core.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_requests', to='core.project')),
            ],
            options={
                'db_table': 'support_requests',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(choices=[('shared', 'Client and support team'), ('internal', 'Support team only')], max_length=10)),
                ('body', models.TextField(max_length=5000)),
                ('request_key', models.UUIDField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('support_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='operations.supportrequest')),
            ],
            options={
                'db_table': 'support_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['status', '-updated_at'], name='support_status_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportmessage',
            constraint=models.CheckConstraint(condition=models.Q(('audience__in', ['shared', 'internal'])), name='valid_support_message_audience'),
        ),
    ]
